name: Update Berlin & Beyond History

on:
  push:
    paths:
      - 'BerlinAndBeyond/**'
  workflow_dispatch:

jobs:
  update-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Append recent commits to history.md
        run: |
          COMMITS=$(git log -n 5 --pretty=format:"- %s" -- BerlinAndBeyond/ | sed 's/"/\\"/g')
          sed -i "/## \[Unreleased\]/a\\\n### Commits\n$COMMITS\n" BerlinAndBeyond/meta/history.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add BerlinAndBeyond/meta/history.md
          git commit -m "docs: update Berlin & Beyond history.md with recent commits" || echo "No changes to commit"
          git push
